version: '2'
services:
  nifi:
    image: sihutch76/nifi
    container_name: nifi
    ports:
      - "8443:8443"
  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: registry
    ports:
      - "18080:18080"
